### ISSUE TITLE
Markdown formatting on README.md

### ISSUE THREAD

**Issue by nicksuch** [brookin8/brookin8.github.io#1]
Hey @brookin8, this looks good! One way you could improve the formatting on your README is to add a space in between the hyphen and the word. For instance: `-GitHub` should be `- GitHub`. By fixing this Markdown formatting, it will make it so that your links all appeared as a bulleted (unordered) list.

**Comment by brookin8** [comment]
Got it, and done! Thanks, Nick!

**Comment by nicksuch** [comment]
Looks great @brookin8! I'm going to mark this issue as "closed"
